import { MD3DarkTheme, MD3LightTheme } from 'react-native-paper';
import type { MD3Theme } from 'react-native-paper';

export const brandColors = {
  background: '#FFFFFF',
  surface: '#F7F7F5',
  surfaceCard: '#FFFFFF',
  surfaceElevated: '#F0EDE5',
  text: '#111111',
  textSecondary: '#4B4B46',
  textMuted: '#8A8A84',
  border: '#E2E0DA',
  borderLight: '#D5D3CC',
  disabled: '#B0B0AA',
  primary: '#111111',
  primaryLight: '#333333',
  primaryDark: '#000000',
  secondary: '#4B4B46',
  secondaryLight: '#6B6B66',
  secondaryDark: '#2E2E2E',
  accent: '#4B4B46',
  accentLight: '#6B6B66',
  accentDark: '#2E2E2E',
  success: '#16794C',
  successLight: '#1A8F59',
  warning: '#B8860B',
  error: '#B42318',
  errorLight: '#D4342A',
  info: '#6B6B66',
  white: '#FFFFFF',
  black: '#000000',
} as const;

export const radius = {
  xs: 4,
  sm: 6,
  md: 8,
  lg: 10,
} as const;

export const darkTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: brandColors.primary,
    primaryContainer: brandColors.surfaceElevated,
    secondary: brandColors.secondary,
    secondaryContainer: brandColors.surface,
    tertiary: brandColors.accent,
    tertiaryContainer: brandColors.surfaceElevated,
    surface: brandColors.surface,
    surfaceVariant: brandColors.surfaceCard,
    background: brandColors.background,
    error: brandColors.error,
    errorContainer: '#FDE9E7',
    onPrimary: brandColors.white,
    onPrimaryContainer: brandColors.text,
    onSecondary: brandColors.white,
    onSecondaryContainer: brandColors.text,
    onSurface: brandColors.text,
    onSurfaceVariant: brandColors.textSecondary,
    onBackground: brandColors.text,
    onError: brandColors.white,
    outline: brandColors.border,
    outlineVariant: brandColors.borderLight,
  },
  roundness: radius.md,
};

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#111111',
    primaryContainer: '#E8E8E2',
    secondary: '#343430',
    secondaryContainer: '#EFEFEA',
    tertiary: '#4B4B46',
    tertiaryContainer: '#F4F4EF',
    surface: '#FFFFFF',
    surfaceVariant: '#F4F4EF',
    background: '#FAFAF6',
    error: brandColors.error,
    errorContainer: '#FDE9E7',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#111111',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#111111',
    onSurface: '#111111',
    onSurfaceVariant: '#4B4B46',
    onBackground: '#111111',
    onError: '#FFFFFF',
    outline: '#D5D5CE',
    outlineVariant: '#E5E5DE',
  },
  roundness: radius.md,
};

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
} as const;

export const typography = {
  h1: { fontSize: 28, fontWeight: '700' as const, lineHeight: 36 },
  h2: { fontSize: 24, fontWeight: '700' as const, lineHeight: 32 },
  h3: { fontSize: 18, fontWeight: '600' as const, lineHeight: 26 },
  body: { fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
  bodySmall: { fontSize: 14, fontWeight: '400' as const, lineHeight: 21 },
  caption: { fontSize: 12, fontWeight: '400' as const, lineHeight: 16 },
  section: {
    fontSize: 12,
    fontWeight: '700' as const,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: 'uppercase' as const,
  },
  button: { fontSize: 15, fontWeight: '700' as const, lineHeight: 22 },
} as const;
